spring:
 profiles:
    active:
    - local
    
---

spring:
 profiles:
  - local
  
 mvc:
   view:
    prefix: "/WEB-INF/views"
    suffix: ".jsp"
    
 datasource:
    url: jdbc:mysql://localhost:3306/yyyy?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true

    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 session:
    jdbc:
      initialize-schema: always

 devtools:
    livereload:
      enabled: true      
      
server:
  port: 8080
  tomcat:
   file-encoding: UTF-8
   
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
     init-parameters:
        development: true
    session:
     timeout: 7200

  error:
    whitelabel:
      enabled: false 

mybatis:
 type-aliases-package: com.lcomputerstudy.example.domain
 mapper-locations: mapper/**/*.xml
 
logging:
 config: classpath:logback-spring.xml